### ISSUE TITLE
Traefik configuration

### ISSUE THREAD

**Issue by mjuarezm** [bjuretko/docker-baikal-infcloud#29]
I am trying to setup `Traefik` to work with `docker-baikal-infcloud`, following the docker-compose script in this [repo](https://github.com/ckulka/baikal-docker/blob/master/examples/docker-compose.ssl.yaml). I am changing the ports to `8800`, but I cannot make it work. This is my modified docker-compose script for traefik:

```
version: "2"
services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - /etc/ssl/private/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --defaultentrypoints=http,https
      - --entrypoints=Name:http Address::8888 TLS Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::8800
      # - --accesslog
      - --acme
      # - --acme.acmelogging
      # Staging CA server for testing/demo purposes
      # - --acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --acme.email=admin@example.com
      - --acme.entrypoint=https
      - --acme.httpchallenge
      - --acme.httpchallenge.entrypoint=http
      - --acme.onhostrule=true
      - --acme.storage=/acme.json
      - --docker
```
When I go to `https://host.com:8888/baikal/html/admin/` it does make an HTTPS connection and I have to accept the certificates but then redirects me to plain HTTP. It seems this is very close to be a working Traefik docker that could be very useful with this repo.
